"""empty message

Revision ID: b9ac026c2a06
Revises: 
Create Date: 2024-12-04 22:14:38.197091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ac026c2a06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('StudentLevel_Bachillerato', 'StudentLevel_Universitario', name='studentlevel'), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=True),
    sa.Column('time_preferences', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('TeacherLevel_TecnicoTerciario', 'TeacherLevel_Licenciatura', 'TeacherLevel_Maestria', 'TeacherLevel_Doctorado', name='teacherlevel'), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=True),
    sa.Column('time_preferences', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('users')
    # ### end Alembic commands ###
